In [1]:
print("TRAINING STARTED")

import pandas as pd
import numpy as np
import time

from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

TRAINING STARTED

In [2]:
data = load_diabetes()
X = pd.DataFrame(data.data, columns=data.feature_names)
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [3]:
models = [
    LinearRegression(),
    RandomForestRegressor(n_estimators=50),
    RandomForestRegressor(n_estimators=100),
    RandomForestRegressor(max_depth=5),

]

In [4]:
from sklearn.tree import DecisionTreeRegressor
models.append(DecisionTreeRegressor())

In [5]:
results = []

best_r2 = -1
best_model = None

for i in range(12):

    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=i)

    model = models[i % len(models)]

    if isinstance(model, RandomForestRegressor):
        model.set_params(
            n_estimators=300,
            max_depth=10,
            random_state=i
        )

    start = time.time()

    model.fit(X_train, y_train)
    preds = model.predict(X_test)

    mae = mean_absolute_error(y_test, preds)
    rmse = np.sqrt(mean_squared_error(y_test, preds))
    r2 = r2_score(y_test, preds)
    mape = np.mean(np.abs((y_test - preds)/y_test)) * 100

    training_time = time.time() - start

    results.append({
        "Run": i,
        "Model": type(model).__name__,
        "MAE": round(mae, 2),
        "RMSE": round(rmse, 2),
        "R2": round(r2, 4),
        "MAPE": round(mape, 2),
        "Time": round(training_time, 4)
    })

    print(f"Run {i} → Model: {type(model).__name__}, R2: {r2:.4f}")

    if r2 > best_r2:
        best_r2 = r2
        best_model = model

import pandas as pd
df_results = pd.DataFrame(results)
df_results

Run 0 → Model: LinearRegression, R2: 0.3594
Run 1 → Model: RandomForestRegressor, R2: 0.2648
Run 2 → Model: RandomForestRegressor, R2: 0.3121
Run 3 → Model: RandomForestRegressor, R2: 0.3717
Run 4 → Model: DecisionTreeRegressor, R2: -0.3748
Run 5 → Model: LinearRegression, R2: 0.5308
Run 6 → Model: RandomForestRegressor, R2: 0.3519
Run 7 → Model: RandomForestRegressor, R2: 0.4858
Run 8 → Model: RandomForestRegressor, R2: 0.3488
Run 9 → Model: DecisionTreeRegressor, R2: 0.0754
Run 10 → Model: LinearRegression, R2: 0.5282
Run 11 → Model: RandomForestRegressor, R2: 0.4978

    Run                  Model    MAE   RMSE      R2   MAPE    Time
0     0       LinearRegression  45.12  56.39  0.3594  37.96  0.0313
1     1  RandomForestRegressor  47.94  61.95  0.2648  36.79  0.8328
2     2  RandomForestRegressor  48.70  60.18  0.3121  38.06  0.6918
3     3  RandomForestRegressor  45.51  57.64  0.3717  43.23  0.6962
4     4  DecisionTreeRegressor  67.76  86.85 -0.3748  54.53  0.0057
5     5       LinearRegression  45.57  55.15  0.5308  37.26  0.0027
6     6  RandomForestRegressor  47.66  60.89  0.3519  40.41  0.7215
7     7  RandomForestRegressor  43.94  55.36  0.4858  39.13  1.2039
8     8  RandomForestRegressor  50.64  61.18  0.3488  45.23  2.0137
9     9  DecisionTreeRegressor  60.65  73.04  0.0754  52.10  0.0244
10   10       LinearRegression  43.72  54.43  0.5282  39.65  0.0069
11   11  RandomForestRegressor  49.12  60.93  0.4978  45.34  1.6815

In [6]:
df_results = pd.DataFrame(results)
df_results

    Run                  Model    MAE   RMSE      R2   MAPE    Time
0     0       LinearRegression  45.12  56.39  0.3594  37.96  0.0313
1     1  RandomForestRegressor  47.94  61.95  0.2648  36.79  0.8328
2     2  RandomForestRegressor  48.70  60.18  0.3121  38.06  0.6918
3     3  RandomForestRegressor  45.51  57.64  0.3717  43.23  0.6962
4     4  DecisionTreeRegressor  67.76  86.85 -0.3748  54.53  0.0057
5     5       LinearRegression  45.57  55.15  0.5308  37.26  0.0027
6     6  RandomForestRegressor  47.66  60.89  0.3519  40.41  0.7215
7     7  RandomForestRegressor  43.94  55.36  0.4858  39.13  1.2039
8     8  RandomForestRegressor  50.64  61.18  0.3488  45.23  2.0137
9     9  DecisionTreeRegressor  60.65  73.04  0.0754  52.10  0.0244
10   10       LinearRegression  43.72  54.43  0.5282  39.65  0.0069
11   11  RandomForestRegressor  49.12  60.93  0.4978  45.34  1.6815

In [7]:
print("Best R2:", best_r2)
print("Best Model:", type(best_model).__name__)

Best R2: 0.5308133103536821
Best Model: LinearRegression